### ISSUE TITLE
Java error on first IP 

### ISSUE THREAD

**Issue by calibrae** [EasyG0ing1/Migration#6]
Hi, 

Getting a Java error 

```
java.net.UnknownHostException:
10.10.0.2
: nodename nor servname provided, or not known
	at java.base@22.0.1/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base@22.0.1/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
	at java.base@22.0.1/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1221)
	at java.base@22.0.1/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1816)
	at java.base@22.0.1/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1149)
	at java.base@22.0.1/java.net.InetAddress.getAllByName0(InetAddress.java:1806)
	at java.base@22.0.1/java.net.InetAddress.getAllByName(InetAddress.java:1676)
	at java.base@22.0.1/java.net.InetAddress.getByName(InetAddress.java:1578)
	at com.simtechdata.migrate.Migrate.ipInSubnet(Migrate.java:541)
	at com.simtechdata.migrate.Migrate.getSubnet(Migrate.java:507)
	at com.simtechdata.migrate.Migrate.createKeaReservations(Migrate.java:354)
	at com.simtechdata.migrate.Migrate.start(Migrate.java:69)
	at com.simtechdata.App.main(App.java:17)
	at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

Here is the relevant xml part

```xml
<staticmap>
<mac>
[[CENSORED]]
</mac>
<cid>
rockyipa
</cid>
<ipaddr>
10.10.0.2
</ipaddr>
<hostname>
rockyipa
</hostname>
<descr>
Rocky Linux Free IPA server
</descr>
<filename/>
<rootpath/>
<defaultleasetime/>
<maxleasetime/>
<gateway/>
<domain>
[[CENSORED]]
</domain>
<domainsearchlist/>
<ddnsdomain/>
<ddnsdomainprimary/>
<ddnsdomainsecondary/>
<ddnsdomainkeyname/>
<ddnsdomainkeyalgorithm>
hmac-md5
</ddnsdomainkeyalgorithm>
<ddnsdomainkey/>
<tftp/>
<ldap/>
<nextserver/>
<filename32/>
<filename64/>
<filename32arm/>
<filename64arm/>
<uefihttpboot/>
<numberoptions/>
</staticmap>
```

**Comment by EasyG0ing1** [comment]
@calibrae - Which platform are you running in? Mac? Windows?...??

**Comment by calibrae** [comment]
Hello, macOS, but I have access to windows or linux machines if needed.

**Comment by EasyG0ing1** [comment]
@calibrae MacOS is fine, that's what I'm using. I'm going to shoot you a different executable that will give us more information if you haven't migrated already...
